# Generated by Django 2.2.12 on 2020-11-05 14:12

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelpractice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsession',
            name='last_round',
            field=otree.db.models.IntegerField(choices=[(2, 2)], null=True),
        ),
    ]
