# Generated by Django 2.2.12 on 2020-10-19 06:23

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_group', to='otree.Session')),
            ],
            options={
                'db_table': 'questionnaire_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'questionnaire_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('gender', otree.db.models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='You consider yourself as:')),
                ('birthyear', otree.db.models.IntegerField(null=True, verbose_name='Your year of birth:')),
                ('country', otree.db.models.LongStringField(max_length=100, null=True, verbose_name='Country where you grew up in:')),
                ('education_level', otree.db.models.IntegerField(choices=[(1, 'Undergraduate'), (2, 'Graduate school'), (3, 'Law school'), (4, 'Other')], null=True, verbose_name='What level of education are you currently pursuing?')),
                ('degree_program', otree.db.models.LongStringField(max_length=100, null=True, verbose_name='What degree program are you currently pursuing?')),
                ('organizations', otree.db.models.LongStringField(max_length=100, null=True, verbose_name='Are you a member of the following organizations? Tick all that apply to you.')),
                ('employed', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Are you currently employed?')),
                ('work_hours', otree.db.models.IntegerField(blank=True, choices=[(1, 'Less than 20 hours'), (2, '20 to 30 hours'), (3, 'More than 30 hours')], null=True, verbose_name='How many hours do you normally work in a week?')),
                ('selling_goods', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Do you have any experience in selling goods?')),
                ('sold_goods', otree.db.models.LongStringField(blank=True, max_length=100, null=True, verbose_name='What did you sell?')),
                ('consumer_benefit_cartel', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='In your opinion, will consumers benefit if sellers of the same or similar goods discuss their offer price?')),
                ('first_thing_cartel', otree.db.models.LongStringField(blank=True, max_length=100, null=True, verbose_name='What is the first thing that comes to mind when you hear the word "cartel"?')),
                ('betting', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Did you engage in any better of gambling activity (e.g., lottery, bingo, poker, card games, horse racing, etc.) in the past 6 months?')),
                ('betting_times', otree.db.models.IntegerField(blank=True, choices=[(1, 'Once'), (2, '2 to 5 times'), (3, '6 to 10 times'), (4, 'More than 10 times')], null=True, verbose_name='How many times did you engage in at least one of these activities in the past 6 months?')),
                ('violate_convenient', otree.db.models.IntegerField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Agree'), (4, 'Strongly agree')], null=True, verbose_name='I am willing to violate a rule if it is convenient for me.')),
                ('violate_unlikely_caught', otree.db.models.IntegerField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Agree'), (4, 'Strongly agree')], null=True, verbose_name='I will violate a rule if it is unlikely that I will be caught.')),
                ('violate_like', otree.db.models.IntegerField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Agree'), (4, 'Strongly agree')], null=True, verbose_name='I like violating rules.')),
                ('violate_harm', otree.db.models.IntegerField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Agree'), (4, 'Strongly agree')], null=True, verbose_name='It is alright to violate a rule if it does not harm anyone.')),
                ('risk_fun', otree.db.models.IntegerField(choices=[(1, '1 (lowest)'), (2, 2), (3, 3), (4, 4), (5, '5 (highest)')], null=True, verbose_name='The greater the risk, the more fun the activity.')),
                ('new_situation', otree.db.models.IntegerField(choices=[(1, '1 (lowest)'), (2, 2), (3, 3), (4, 4), (5, '5 (highest)')], null=True, verbose_name='I like the feeling that comes from entering a new situation.')),
                ('immoral', otree.db.models.IntegerField(choices=[(1, '1 (lowest)'), (2, 2), (3, 3), (4, 4), (5, '5 (highest)')], null=True, verbose_name='I do not let the fact that something is considered immoral to stop me from doing it.')),
                ('illegal', otree.db.models.IntegerField(choices=[(1, '1 (lowest)'), (2, 2), (3, 3), (4, 4), (5, '5 (highest)')], null=True, verbose_name='I do not let the fact that something is illegal to stop me from doing it.')),
                ('society', otree.db.models.IntegerField(choices=[(1, '1 (lowest)'), (2, 2), (3, 3), (4, 4), (5, '5 (highest)')], null=True, verbose_name='I often think about doing things that I know society would disapprove of')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Subsession')),
            ],
            options={
                'db_table': 'questionnaire_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Subsession'),
        ),
    ]
