# Generated by Django 2.2.12 on 2020-10-31 06:49

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelgame', '0002_subsession_reputation_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsession',
            name='reputation_num',
        ),
        migrations.AddField(
            model_name='group',
            name='reputation_num',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
