# Generated by Django 2.2.12 on 2020-11-02 12:51

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelgame', '0003_auto_20201031_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='common_price',
            field=otree.db.models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True, verbose_name='What price did you agree on?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='price',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True),
        ),
    ]
